name: destroy-infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
      TF_VAR_pipeout_bucket_name: ${{ secrets.TF_VAR_PIPEOUT_BUCKET_NAME }}
      TF_VAR_airflow_image: ${{ secrets.TF_VAR_AIRFLOW_IMAGE }}
      TF_VAR_model_training_image: ${{ secrets.TF_VAR_MODEL_TRAINING_IMAGE }}
      TF_VAR_feature_engineering_image: ${{ secrets.TF_VAR_FEATURE_ENGINEERING_IMAGE }}
      TF_VAR_mlflow_image: ${{ secrets.TF_VAR_MLFLOW_IMAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: opentofu/setup-opentofu@v1

      - name: Terraform Init
        run: tofu init

      - name: Terraform Destroy
        run: tofu destroy -input=false -auto-approve
