name: tofu

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tofu:
    runs-on: ubuntu-latest

    env:
      aws_region: $ {{ secrets.TF_VAR_AWS_REGION}}
      feature_engineering_image: $ {{ secrets.TF_VAR_FEATURE_ENGINEERING_IMAGE}}
      airflow_image: $ {{ secrets.TF_VAR_AIRFLOW_IMAGE}}
      mlflow_image: $ {{ secrets.TF_VAR_MLFLOW_IMAGE}}
      model_training_image: $ {{ secrets.TF_VAR_MODEL_TRAINING_IMAGE}}
      pipeout_bucket_name: ${{secrets.TF_VAR_PIPEOUT_BUCKET_NAME}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

      - name: Setup Terraform
        uses: opentofu/setup-opentofu@v1

      - name: Terraform Init
        run: tofu init

      - name: Terraform Plan
        run: tofu plan

      - name: Terraform Apply
        run: tofu apply -auto-approve
