name: tofu

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tofu:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
      TF_VAR_pipeout_bucket_name: ${{ secrets.TF_VAR_PIPEOUT_BUCKET_NAME }}
      TF_VAR_airflow_image: ${{ secrets.TF_VAR_AIRFLOW_IMAGE }}
      TF_VAR_model_training_image: ${{ secrets.TF_VAR_MODEL_TRAINING_IMAGE }}
      TF_VAR_feature_engineering_image: ${{ secrets.TF_VAR_FEATURE_ENGINEERING_IMAGE }}
      TF_VAR_mlflow_image: ${{ secrets.TF_VAR_MLFLOW_IMAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: 1.11.6

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        run: tofu plan -input=false

      - name: Tofu Apply
        run: tofu apply -input=false -auto-approve
      - name: Print Load Balancer URL
        run: |
          echo "Airflow URL: $(tofu output -raw airflow_url)"
          echo "MLflow URL:  $(tofu output -raw mlflow_url)"
